site_name: CTO framework
site_url: https://ctoframework.com
repo_url: https://github.com/ctoframework/static-website
edit_uri: edit/main/docs/

copyright: Copyright © 2025

theme:
  name: material
  custom_dir: overrides

  logo: images/ctoframework-logo.png
  favicon: images/ctoframework-logo.ico

  features:
    - navigation.tabs
#    - navigation.expand
    - navigation.indexes
    - navigation.path # Requires insiders build
    - navigation.footer
    - content.action.edit
    - content.code.copy

  palette: 
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - styles/extra.css

extra_javascript:
  - scripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - meta
  - tags
  - search
  - awesome-nav
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true
          site_name: "Documentation du plugin MkDocs static i18n (fr)"
          site_description: "Description Française"
          nav_translations:
            Home: Inicio 
            People: Personas 
            Delivery: Procesos
            Product: Producto
            Technology: Tecnología
            Finance: Finanzas
            Resources: Recursos
  - git-revision-date-localized:
      enable_creation_date: false

markdown_extensions:
  - def_list
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Español
      link: /es/
      lang: es
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ctoframework
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ctoframework/
    - icon: fontawesome/brands/github
      link: https://github.com/ctoframework
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ctoframework
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
