site_name: CTO Framework
site_description: The most comprehensive site for technical leaders looking to expand their knowledge and skills.
site_url: https://ctoframework.com
repo_url: https://github.com/ctoframework/static-website
edit_uri: edit/main/docs/

copyright: >
  Copyright &copy; 2025 -
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  custom_dir: overrides

  logo: images/ctoframework-logo.png
  favicon: images/ctoframework-logo.ico

  features:
    - navigation.tabs
#    - navigation.expand
    - navigation.indexes
    - navigation.path # Requires insiders build
    - navigation.footer
    - content.action.edit
    - content.code.copy

  palette: 
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - styles/extra.css

extra_javascript:
  - scripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - meta
  - tags
  - search
  - social
  - awesome-nav
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true      
  - privacy
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true
          site_description: "El sitio más completo para líderes técnicos que buscan expandir sus conocimientos y habilidades."
          nav_translations:
            Home: Inicio 
            People: Personas 
            Delivery: Procesos
            Product: Producto
            Technology: Tecnología
            Finance: Finanzas
            Resources: Recursos
  - git-revision-date-localized:
      enable_creation_date: false

markdown_extensions:
  - def_list
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Español
      link: /es/
      lang: es
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ctoframework
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ctoframework/
    - icon: fontawesome/brands/github
      link: https://github.com/ctoframework
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ctoframework
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

hooks:
  - hooks/socialmedia.py
  - hooks/extlinks.py

validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
